
development:
  adapter: mysql
  database: intermediate_bare_bones
  username: root
  password: t1m0
  host: localhost
  pool: 5
  timeout: 5000

test:

production:
  adapter: mysql2
  database: migration
  username: root
  password: letusout!
  host: localhost
  pool: 5
  timeout: 5000
  
bart:
  adapter: mysql
  database: bart_migration_trial
  username: root
  password: t1m0
  host: localhost
  pool: 5
  timeout: 5000
