
development:
  adapter: mysql
  database: bart1_intermediate_bare_bones
  password: mlambe
  host: localhost
  pool: 5
  timeout: 5000

test:

production:
  adapter: mysql2
  database: migration
  password: letusout!
  host: localhost
  pool: 5
  timeout: 5000
  
bart:
  adapter: mysql
  database: test_st_gebriels1
  password: mlambe
  host: localhost
  pool: 5
  timeout: 5000
