class CreateHivStagingEncounters < ActiveRecord::Migration
  def self.up

ActiveRecord::Base.connection.execute <<EOF
DROP TABLE IF EXISTS `hiv_staging_encounters`;
EOF

ActiveRecord::Base.connection.execute <<EOF
create table `hiv_staging_encounters`(
`id` int auto_increment not null primary key,
`visit_encounter_id` int not null,
`old_enc_id` int not null,
`patient_id` int not null,
`patient_pregnant` varchar(25) ,
`patient_breast_feeding` varchar(25),
`cd4_count_available` varchar(25),
`cd4_count` int,
`cd4_count_modifier` varchar(5),
`cd4_count_percentage` double,
`date_of_cd4_count` date,
`asymptomatic` varchar(25),
`persistent_generalized_lymphadenopathy` varchar(25),
`unspecified_stage_1_cond` varchar(25),
`molluscumm_contagiosum` varchar(25),
`wart_virus_infection_extensive` varchar(25),
`oral_ulcerations_recurrent` varchar(25),
`parotid_enlargement_persistent_unexplained` varchar(25),
`lineal_gingival_erythema` varchar(25),
`herpes_zoster` varchar(25),
`respiratory_tract_infections_recurrent` varchar(25),
`unspecified_stage2_condition` varchar(25),
`angular_chelitis` varchar(25),
`papular_prurtic_eruptions` varchar(25),
`hepatosplenomegaly_unexplained` varchar(25),
`oral_hairy_leukoplakia` varchar(25),
`severe_weight_loss` varchar(25),
`fever_persistent_unexplained` varchar(25),
`pulmonary_tuberculosis` varchar(25),
`pulmonary_tuberculosis_last_2_years` varchar(25),
`severe_bacterial_infection` varchar(25),
`bacterial_pnuemonia` varchar(25),
`symptomatic_lymphoid_interstitial_pnuemonitis` varchar(25),
`chronic_hiv_assoc_lung_disease` varchar(25),
`unspecified_stage3_condition` varchar(25),
`aneamia` varchar(25),
`neutropaenia` varchar(25),
`thrombocytopaenia_chronic` varchar(25),
`diarhoea` varchar(25),
`oral_candidiasis` varchar(25),
`acute_necrotizing_ulcerative_gingivitis` varchar(25),
`lymph_node_tuberculosis` varchar(25),
`toxoplasmosis_of_brain` varchar(25),
`cryptococcal_meningitis` varchar(25),
`progressive_multifocal_leukoencephalopathy` varchar(25),
`disseminated_mycosis` varchar(25),
`candidiasis_of_oesophagus` varchar(25),
`extrapulmonary_tuberculosis` varchar(25),
`cerebral_non_hodgkin_lymphoma` varchar(25),
`kaposis` varchar(25),
`hiv_encephalopathy` varchar(25),
`bacterial_infections_severe_recurrent` varchar(25),
`unspecified_stage_4_condition` varchar(25),
`pnuemocystis_pnuemonia` varchar(25),
`disseminated_non_tuberculosis_mycobactierial_infection` varchar(25),
`cryptosporidiosis` varchar(25),
`isosporiasis` varchar(25),
`symptomatic_hiv_asscoiated_nephropathy` varchar(25),
`chronic_herpes_simplex_infection` varchar(25),
`cytomegalovirus_infection` varchar(25),
`toxoplasomis_of_the_brain_1month` varchar(25),
`recto_vaginal_fitsula` varchar(25),
`hiv_wasting_syndrome` varchar(25),
`cryptococcal_meningitis_or_other_eptb_cryptococcosis` varchar(25),
`candidiasis_of_oesophagus_trachea_bronchi_or_lungs` varchar(25),
`severe_unexplained_wasting_malnutrition` varchar(25),
`diarrhoea_chronic_less_1_month_unexplained` varchar(25),
`moderate_weight_loss_10_unexplained` varchar(25),
`cd4_percentage_available` varchar(25),
`acute_necrotizing_ulcerative_stomatitis_gingivitis_or_period` varchar(25),
`moderate_unexplained_wasting_malnutrition` varchar(25),
`diarrhoea_persistent_unexplained_14_days_or_more` varchar(25),
`acute_ulcerative_mouth_infections` varchar(25),
`anaemia_unexplained_8_g_dl` varchar(25),
`atypical_mycobacteriosis_disseminated_or_lung` varchar(25),
`bacterial_infections_sev_recurrent_excluding_pneumonia` varchar(25),
`cancer_cervix` varchar(25),
`chronic_herpes_simplex_infection_genital` varchar(25),
`cryptosporidiosis_chronic_with_diarrhoea` varchar(25),
`cytomegalovirus_infection_retinitis_or_other_organ` varchar(25),
`cytomegalovirus_of_an_organ_other_than_liver` varchar(25),
`fungal_nail_infections` varchar(25),
`herpes_simplex_infection_mucocutaneous_visceral` varchar(25),
`hiv_associated_cardiomyopathy` varchar(25),
`hiv_associated_nephropathy` varchar(25),
`invasive_cancer_cervix` varchar(25),
`isosporiasis_1_month` varchar(25),
`leishmaniasis_atypical_disseminated` varchar(25),
`minor_mucocutaneous_manifestations_seborrheic_dermatitis` varchar(25),
`moderate_unexplained_malnutrition` varchar(25),
`molluscum_contagiosum_extensive` varchar(25),
`non_typhoidal_salmonella_bacteraemia_recurrent` varchar(25),
`oral_candidiasis_from_age_2_months` varchar(25),
`oral_thrush` varchar(25),
`perform_extended_staging` varchar(25),
`pneumocystis_carinii_pneumonia` varchar(25),
`pneumonia_severe` varchar(25),
`recurrent_bacteraemia_or_sepsis_with_nts` varchar(25),
`recurrent_severe_presumed_pneumonia` varchar(25),
`recurrent_upper_respiratory_tract_bac_sinusitis` varchar(25),
`seborrhoeic_dermatitis` varchar(25),
`sepsis_severe` varchar(25),
`tb_lymphadenopathy` varchar(25),
`unexplained_anaemia_neutropenia_or_thrombocytopenia` varchar(25),
`visceral_leishmaniasis` varchar(25),
`reason_for_starting_art` varchar(25),
`who_stage` varchar(255),
`location` varchar(255),
`voided` tinyint(1) not null default 0,
`void_reason` varchar(255), 
`date_voided` date,
`voided_by` int(11),
`encounter_datetime` datetime,
`date_created` datetime,
`creator` varchar(255)

);
EOF
  end

  def self.down
    drop_table :hiv_staging_encounters
  end
end
